name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Windows is not supported by the Rite language server at this time.

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - run: |
          npx @vscode/vsce package --target darwin-arm64
          npx @vscode/vsce package --target darwin-x64
          npx @vscode/vsce package --target linux-x64
          npx @vscode/vsce package --target linux-arm64
      - uses: actions/upload-artifact@v4
        with:
          name: vsix-packages
          path: "*.vsix"
          retention-days: 3
